### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by zephyrcicd** [lin2j/simple-deployment#12]
![image](https://github.com/user-attachments/assets/456f52a4-5ac0-4e9c-a906-00474a61774d)
![image](https://github.com/user-attachments/assets/f8009195-3ca5-4d6b-9af1-983d9fc8fb12)

Version 1.3.7 is not compatible with the latest IDEA2024.2 2024.2.0.1

**Comment by lin2j** [comment]
这次的版本是适用于 2019.3 - 2023.7 之间的版本的。

2024.1 以上的版本，因为加了个慢操作的检测，需要所有的 AnAction 子类实现 `getActionUpdateThread` 方法，目前还在看那些地方需要实现这个方法，所以会晚一点发布。不实现这个方法的话，偶尔会有一些异常信息，但是不影响功能。

我给自己打了个 2024.1+ 的版本，这几天放在自己的日常工作中测试。
[Easy-Deploy-1.3.7-241.zip](https://github.com/user-attachments/files/16661662/Easy-Deploy-1.3.7-241.zip)
