### ISSUE TITLE
选择Profile页面UI黑线问题

### ISSUE THREAD

**Issue by zephyrcicd** [lin2j/simple-deployment#15]
<img width="370" alt="image" src="https://github.com/user-attachments/assets/e1534411-fde2-46d5-99ac-cc4320094e37">

在192.168.100.87这个位置，不知道为啥会有一条黑线，当然 这个不影响使用

**Comment by lin2j** [comment]
这个倒是没遇到过，像是 UI 渲染问题，重启 IDE 还会存在吗？

**Comment by zephyrcicd** [comment]
> 这个倒是没遇到过，像是 UI 渲染问题，重启 IDE 还会存在吗？

是的，重启还是存在
